"""Added initial table

Revision ID: 30d9424d6cd2
Revises: 222961c31523
Create Date: 2022-09-02 03:18:29.633827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d9424d6cd2'
down_revision = '222961c31523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    # ### end Alembic commands ###
