"""added cpu_info table

Revision ID: 8095f0d37740
Revises: 89d0df09e3cb
Create Date: 2022-09-03 22:28:11.366952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8095f0d37740'
down_revision = '89d0df09e3cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu_info',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('workload', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.drop_table('temperatures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('temp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('datetime', name='temperatures_pkey')
    )
    op.drop_table('cpu_info')
    # ### end Alembic commands ###
