"""Added initial table

Revision ID: 89d0df09e3cb
Revises: 30d9424d6cd2
Create Date: 2022-09-02 17:31:23.382907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89d0df09e3cb'
down_revision = '30d9424d6cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.drop_table('temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('temp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('datetime', name='temperature_pkey')
    )
    op.drop_table('temperatures')
    # ### end Alembic commands ###
