"""Added initial table

Revision ID: 997378f261f5
Revises: 
Create Date: 2022-09-01 22:33:56.789037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997378f261f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('temp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('temp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    # ### end Alembic commands ###
